### ISSUE TITLE
how to use 'noop' primitive in smalltalk

### ISSUE THREAD

**Issue by YeesterPlus** [squeak-smalltalk/squeak-object-memory#125]
how to use nop in smalltalk?

**Comment by krono** [comment]
Hey @YeesterPlus, This issue tracker is mostly for tracking bugs in the Squeak Object memory aka Image.
If you need help or advise in _using_ or _programming with_ Squeak, you'll find loads of documentation here: https://squeak.org/documentation/ and resources how to engage with the community here: https://squeak.org/community/

**Comment by LinqLover** [comment]
@YeesterPlus We have decided in a board meeting that questions in the issue tracker are welcome. So if your question is not yet resolved, please feel free to reopen it and describe it a little bit more so we can help out!

**Comment by eliotmiranda** [comment]
@YeesterPlus the nop bytecode can be used to pad bytecode methods to make room for modifications to the bytecode. This feature was used at Cadence to implement a line-number oriented breakpointing facility for a scripting language implemented above Newspeak, itself implemented above Squeak Smalltalk.  Since the nop can take extensions it can also be used to put metadata into the bytecode. It may have other uses.

HTH
